name: CI/CD React with Jest

on:
  push:
    branches:
      - dev 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Installation des dépendances
      run: npm install

    - name: Exécution des tests Jest
      run: npm run test

    - name: Fusion des modifications de dev dans la branche par défaut
      if: success() && github.ref == 'refs/heads/dev'
      run: |
        git checkout ${{ github.head_ref }}
        git pull origin ${{ github.head_ref }}
        git merge dev
        git push origin ${{ github.head_ref }}

    - name: Déploiement sur le VPS
      if: success() && github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd docker/inventory-back
          sudo rm -r inventory-back
          git clone https://github.com/Killianlecorf/inventory-back
          cd inventory-back
          sudo npm install
          sudo npm run build
          sudo docker-compose -f Docker-compose.yml up --build -d

