name: CI/CD React with Jest

on:
  push:
    branches:
      - dev 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Installation des dépendances
      run: npm install

    - name: Exécution des tests Jest
      run: npm run test

    - name: Fusion des modifications de dev dans main
      if: success() && github.ref == 'refs/heads/dev'
      run: |
        git checkout main
        git pull origin main
        git merge dev
        git push origin main

    - name: Déploiement sur le VPS
      if: success() && github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd docker/inventory-back
          sudo git pull origin main
          sudo npm install
          sudo npm i --save-dev @types/dotenv
          sudo npm run build

